function u = gen_input()
% Senal de entrada rica (misma estructura st/zt de los scripts originales)
% Excita variados escalones y niveles para exponer la dinamica del sistema.
st = [ 1 1 1 1 1 1 ];
zt = [ 0 0 0 0 0 0 ];
u = [st st zt -st -st -0.2*st -0.4*st -0.6*st zt st 0.8*st 0.5*st st 0.2*st zt ...
     -st -st -st zt zt zt st st -st -st -st zt zt 0.25*st st 0.75*st st zt zt zt ...
     zt zt zt zt -st -st st st -st -st st 0.1*st 0.1*st st -st st -0.3*st 0.3*st ...
     st -st -st st st -st -st st st st -st -st -st st st st -st -st -st st st st st ...
     -st -st -st -st st st st st -st -st -st -st st st st st st -0.1*st -0.3*st ...
     -0.5*st -0.7*st -0.9*st 0.9*st 0.7*st 0.5*st 0.3*st 0.1*st -st -st -st -st ...
     -st st st st st st ];
u = u';
end
